---
- hosts: local
  connection: local
  vars_files:
    - vars/defaults.yml

  tasks:
    # - name: Create security group
    #   local_action:
    #     module: ec2_group
    #     name: web-security-group
    #     description: Access web-security-group
    #     region: "{{ ec2_region }}"
    #     rules:
    #       - proto: tcp
    #         from_port: 22
    #         to_port: 22
    #         cidr_ip: 0.0.0.0/0
    #       - proto: tcp
    #         from_port: 80
    #         to_port: 80
    #         cidr_ip: 0.0.0.0/0
    #       - proto: tcp
    #         from_port: 443
    #         to_port: 443
    #         cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        instance_tags:
          key: name
          value: "{{ rails.app }}"
        region: "{{ ec2_region }}"
        zone: "{{ ec2_zone }}"
        keypair: "{{ ec2_keypair }}"
        group: "{{ ec2_security_group }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        count: "{{ec2_instance_count }}"
        wait: yes
      register: ec2

    - name: Add instance to local host group
      local_action: lineinfile dest=hosts regexp="{{ item.public_dns_name }}" insertafter="[launched]" line="{{ item.public_dns_name }}"
      with_items: ec2.instances

    # - name: Add instances to host group
    #   local_action: add_host hostname={{item.public_dns_name}} groupname={{security-group}}
    #   with_items: ec2.instances

